### ISSUE TITLE
how to inject to controller and log 

### ISSUE THREAD

**Issue by kishoretvk** [nreco/logging#1]
ijnect to controller and create new file log on a particular exception 

can u please elaborate 

how do we inject to a controller and log it , request and response as json

**Comment by kishoretvk** [comment]
all the logs are piling to one file and they ar enote seperated , is there a way we can speperate them

**Comment by VitaliyMF** [comment]
@kishoretvk FileLoggerProvider writes all messages into single file. 
Current implementation doesn't support separate log files for different log messages, but this feature may be added; feel free to share your needs or ideas on this.

**Comment by kishoretvk** [comment]
thanks for your reply, we will have to work on adding new files each day / per some time,


can we inject this as a service and use it inside controlle to log ? as other loggers ?

**Comment by VitaliyMF** [comment]
> we will have to work on adding new files each day / per some time,

I guess you mean "rolling log file" feature; it also can be added to the FileLoggerProvider; let me know if you interested in this feature (I guess it can be combined with "separate log files for different log messages" you mentioned before).

> can we inject this as a service and use it inside controlle to log ? as other loggers ?

FileLoggerProvider is used with standard .NET Core logging infrastructure and you use it in a standard way (by injecting ILogger<T> into your controllers or services as described in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging ).

**Comment by kishoretvk** [comment]
okay , i will do the rolling log  feature and will update  it :)

**Comment by VitaliyMF** [comment]
I guess this issue is no longer actual:

* rolling file feature was added in #3  (for now new log file is created only when file size limit is specified)
* it is possible to configure several instances of FileLoggerProvider and use MVC Core 2 filtering rules to use different files for different log messages
