### ISSUE TITLE
Can't Get it to log anything...

### ISSUE THREAD

**Issue by Vaccano** [nreco/logging#12]
I am trying to setup basic logging to a file.  I followed the documention on the main page and it makes a log file called `app.log`.  But it only ever logs startup stuff::

> 2020-04-03T15:56:06.2621145-06:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2020-04-03T15:56:06.2656741-06:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Development
2020-04-03T15:56:06.2669093-06:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: C:\my\project\path\here

I setup my `appsettings.json` like this:

    "Logging": {
      "LogLevel": {
        "Default": "Debug",
        "System": "Debug",
        "Microsoft": "Debug"
      },
      "File": {
        "Path": "app.log",
        "Append": "True",
        "FileSizeLimitBytes": 1000000, 
        "MaxRollingFiles": 5 
      }
    }

And I have this in my `ConfigureServices` method in Startup.cs:

     services.AddLogging(loggingBuilder =>
     {
          var loggingSection = Configuration.GetSection("Logging");
          loggingBuilder.AddFile(loggingSection);
     });

And lastly, in one of my classes I have this:
```
private readonly Microsoft.Extensions.Logging.ILogger<MyClassNameHere> fileLog;

public MyClassNameHere( Microsoft.Extensions.Logging.ILogger<MyClassNameHere> fileLog)
{
     this.fileLog = fileLog;
}

public async Task<MyResponse> DoSomething()
{
     fileLog.LogDebug("Log Stuff");
}
```

A few notes:

* I can see that the nroc logger is attached to the `ILogger` instance and has the min log level set to debug.
* I can also see that the other settings from the config file are present in the logger.

**What am I missing to get this to log to a file?**

**Comment by Vaccano** [comment]
So, with some more trial and error I am fairly sure this is an issue of me not understanding how to configure log level.  If I add `log.LogError` calls, those show up.  So do `LogInformation` calls.

Just LogDebug is not showing up.

**Comment by VitaliyMF** [comment]
This is not related to the FileLoggingProvider, this is how logging works by default: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-level

Levels below "Information" are not logged by default, to include them into the log you need to set "Debug" log level explicitly for your namespace/classes in your "Logging":"LogLevel" configuration section.

**Comment by Vaccano** [comment]
Thank you for your response.  Sorry to have bothered you with a question that was not project related!

By the way, your logging library worked fantastic for me!
