### ISSUE TITLE
How to set filename to reset every midnight

### ISSUE THREAD

**Issue by xalexslx** [nreco/logging#14]
Hi,

I would like to my logs to be writable to a file which represents the current day (`Log_yyyy-mm-dd.log`). It is possible to achieve this with some configuration? Also, I would need to change the current filename if the application is running and it get past midnight. Therefore at 00:00:00 it would start writing to the next file.

Any help would be appreciated.

**Comment by VitaliyMF** [comment]
You cannot do that in NReco.Logging.File 1.0.x, but I found that this sounds like a cool feature so I've just added a new capability that is rolled out in a new version 1.1.0. In short, now it is possible to specify custom log file name formatting handler, and if file name  changes in time FileLoggingProvider handles that correctly.

To create a new log file per day:

```
services.AddLogging(loggingBuilder => {
	loggingBuilder.AddFile("app_{0:yyyy}-{0:MM}-{0:dd}.log", fileLoggerOpts => {
		fileLoggerOpts.FormatLogFileName = fName => {
			return String.Format(fName, DateTime.UtcNow);
		};
	});
});
```

With a full path to the log file, directory for the log file also can change in time.
