### ISSUE TITLE
LogDebug does not work

### ISSUE THREAD

**Issue by evomation** [nreco/logging#17]
Hi,

unfortunately LogDebug does not work. 

My configuration:
```
// appsettings.json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Error"
    },
    "File": {
      "Path": "app.log",
      "Append": "True",
      "FileSizeLimitBytes": 10485760, // 10 * 1024 * 1024 => 10MB
      "MaxRollingFiles": 3 // use to specify max number of log files
    }
  },
  "AllowedHosts": "*"
}
```

```
// Startup.cs
services.AddLogging(loggingBuilder => {                
  var loggingSection = Configuration.GetSection("Logging");
  loggingBuilder.AddFile(loggingSection);
});
```

The calls:
```
_logger.LogInformation("INFORMATION");
_logger.LogDebug("DEBUG");
_logger.LogWarning("WARN");
_logger.LogCritical("CRIT");
_logger.LogError("ERROR");
```

The result:
```
2020-11-27T12:31:36.2114667+01:00	INFO	[My.Controllers.MyController]	[0]	INFORMATION
2020-11-27T12:31:36.2345011+01:00	WARN	[My.Controllers.MyController]	[0]	WARN
2020-11-27T12:31:36.2375962+01:00	CRIT	[My.Controllers.MyController]	[0]	CRIT
2020-11-27T12:31:36.2403344+01:00	FAIL	[My.Controllers.MyController]	[0]	ERROR
```

Does anyone have an idea what I am doing wrong?

**Comment by VitaliyMF** [comment]
LogDebug definitely works, however it looks like "Default":"Debug" doesn't set default logging level for some reason.

Could you confirm that you see "DEBUG" log message in the console but it is missed in the file?

**Comment by evomation** [comment]
Hi Vitaliy,

unfortunately, the debug message does not appear in the console. When I use `Console.WriteLine("MSG");` the messasge appears in the console.

Some info about my environment:
- NReco:logging.File V1.1.1
- .NET Core 3.1
- simpe web API project
- VS 2019

Even in a new project the debug messaging does not work. Am I missing some settings?

**Comment by VitaliyMF** [comment]
I mean standard "Console" logging provider here that is added with 
```
loggingBuilder.AddConsole();
```
Why I'm asking about that: log messages filtering is performed outside concrete logging providers (by the Microsoft.Extensions.Logging infrastructure), and this is out of logging provider control. 

However, each logging provider may have it's own 'minimal level'. In case of FileLoggerProvider it is controlled with `FileLoggerProvider.MinLevel` (default value is 'Information'); also it can be set in 'appsettings.json' with

```
"File": {
      "LogLevel": "Debug",
      "Path": "app.log",
      "Append": "True",
      "FileSizeLimitBytes": 10485760, // 10 * 1024 * 1024 => 10MB
      "MaxRollingFiles": 3 // use to specify max number of log files
 }
```

**Comment by evomation** [comment]
It seems to be a deeper problem, because I don't see debug messages even without your LogProvider. I'm on it and grateful for any help.

**Comment by evomation** [comment]
I managed to see the messages in output-window (debug-tab):
```
WebApplication1.Controllers.WeatherForecastController: Information: INFORMATION
WebApplication1.Controllers.WeatherForecastController: Debug: DEBUG
WebApplication1.Controllers.WeatherForecastController: Warning: WARN
WebApplication1.Controllers.WeatherForecastController: Critical: CRIT
WebApplication1.Controllers.WeatherForecastController: Error: ERROR
```

But there are still missing the log file.
```
2020-11-30T10:44:05.3937768+01:00	INFO	[WebApplication1.Controllers.WeatherForecastController]	[0]	INFORMATION
2020-11-30T10:44:05.4020788+01:00	WARN	[WebApplication1.Controllers.WeatherForecastController]	[0]	WARN
2020-11-30T10:44:05.4046834+01:00	CRIT	[WebApplication1.Controllers.WeatherForecastController]	[0]	CRIT
2020-11-30T10:44:05.4078748+01:00	FAIL	[WebApplication1.Controllers.WeatherForecastController]	[0]	ERROR
```

I changed my appsetting.json to
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Debug",
      "Microsoft.Hosting.Lifetime": "Debug"
    },
    "Debug": {
      "LogLevel": {
        "Default": "Debug",
        "System": "Debug",
        "Microsoft": "Information"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Debug",
        "System": "Debug",
        "Microsoft": "Information"
      }
    },
    "File": {
      "LogLevel": "Debug",
      "Path": "app.log",
      "Append": "True",
      "FileSizeLimitBytes": 10485760, // 10 * 1024 * 1024 => 10MB
      "MaxRollingFiles": 3 // use to specify max number of log files
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by VitaliyMF** [comment]
I've just checked the code and it looks like 

```
    "File": {
      "LogLevel": "Debug",
    }

```
was only for .NET Core 1.x, and in case of .NET Core 2.x and 3.x no way to change a `FileLoggerProvider.MinLevel` (which is actually 'DEBUG' by default - see https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerProvider.cs). 

This means that messages filtering is performed on the infrastructure side. I've just checked this configuration:

```
services.AddLogging(loggingBuilder => {
  var loggingSection = Configuration.GetSection("Logging");
  loggingBuilder.AddConfiguration(loggingSection);
  loggingBuilder.AddConsole();
  loggingBuilder.AddFile(loggingSection, fileLoggerOpts => {
  });
});
```

```
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Error"
    },
    "File": {"Path":"app.log"}
  },
```

and I see debug messages in the file, so I cannot reproduce the issue.

**Comment by filipemagomes** [comment]
> 
> 
> Hi,
> 
> unfortunately LogDebug does not work.
> 
> My configuration:
> 
> ```
> // appsettings.json
> {
>   "Logging": {
>     "LogLevel": {
>       "Default": "Debug",
>       "System": "Debug",
>       "Microsoft": "Error"
>     },
>     "File": {
>       "Path": "app.log",
>       "Append": "True",
>       "FileSizeLimitBytes": 10485760, // 10 * 1024 * 1024 => 10MB
>       "MaxRollingFiles": 3 // use to specify max number of log files
>     }
>   },
>   "AllowedHosts": "*"
> }
> ```
> 
> ```
> // Startup.cs
> services.AddLogging(loggingBuilder => {                
>   var loggingSection = Configuration.GetSection("Logging");
>   loggingBuilder.AddFile(loggingSection);
> });
> ```
> 
> The calls:
> 
> ```
> _logger.LogInformation("INFORMATION");
> _logger.LogDebug("DEBUG");
> _logger.LogWarning("WARN");
> _logger.LogCritical("CRIT");
> _logger.LogError("ERROR");
> ```
> 
> The result:
> 
> ```
> 2020-11-27T12:31:36.2114667+01:00	INFO	[My.Controllers.MyController]	[0]	INFORMATION
> 2020-11-27T12:31:36.2345011+01:00	WARN	[My.Controllers.MyController]	[0]	WARN
> 2020-11-27T12:31:36.2375962+01:00	CRIT	[My.Controllers.MyController]	[0]	CRIT
> 2020-11-27T12:31:36.2403344+01:00	FAIL	[My.Controllers.MyController]	[0]	ERROR
> ```
> 
> Does anyone have an idea what I am doing wrong?

Hi,

I have the same problem on .NET Core 5.

I changed the file FileLoggerExtensions.cs on CreateFromConfiguration method to read default LogLevel.
```
// FileLoggerExtensions.cs
private static FileLoggerProvider CreateFromConfiguration(IConfiguration configuration, Action<FileLoggerOptions> configure)
        {
            var fileSection = configuration.GetSection("File");
            if (fileSection == null)
                return null;  // file logger is not configured
            var fileName = fileSection["Path"];
            if (String.IsNullOrWhiteSpace(fileName))
                return null; // file logger is not configured

            var fileLoggerOptions = new FileLoggerOptions();
            var appendVal = fileSection["Append"];
            if (!String.IsNullOrEmpty(appendVal) && bool.TryParse(appendVal, out var append))
                fileLoggerOptions.Append = append;

            var fileLimitVal = fileSection["FileSizeLimitBytes"];
            if (!String.IsNullOrEmpty(fileLimitVal) && Int64.TryParse(fileLimitVal, out var fileLimit))
                fileLoggerOptions.FileSizeLimitBytes = fileLimit;

            var maxFilesVal = fileSection["MaxRollingFiles"];
            if (!String.IsNullOrEmpty(maxFilesVal) && Int32.TryParse(maxFilesVal, out var maxFiles))
                fileLoggerOptions.MaxRollingFiles = maxFiles;

            if (configure != null)
                configure(fileLoggerOptions);

            var provider = new FileLoggerProvider(fileName, fileLoggerOptions);

            // Get LogLevel from Default category or File category
            // File category takes precedence over default category

            var logLevelSection = configuration.GetSection("LogLevel");

            if (logLevelSection != null && logLevelSection["File"] != null)
            {
                var logLevelValue = provider.MinLevel;
                Enum.TryParse(logLevelSection["File"], ignoreCase: true, result: out logLevelValue);

                provider.MinLevel = logLevelValue;
            }
            else if (logLevelSection != null && logLevelSection["Default"] != null)
            {
                var logLevelValue = provider.MinLevel;
                Enum.TryParse(logLevelSection["Default"], ignoreCase: true, result: out logLevelValue);

                provider.MinLevel = logLevelValue;
            }

            return provider;
        }
 ```

**Comment by VitaliyMF** [comment]
Sorry, but I don't understand what is the purpose of setting `provider.MinValue`? Its default value is LogLevel.Debug: https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerProvider.cs
so FilterLoggerProvider doesn't filter anything on its side - and normally filtering is performed by the logging infrastructure that takes into account "Logging":"LogLevel" config section (it is NOT intended for reading by the logging provider implementations).

**Comment by filipemagomes** [comment]
> 
> 
> Sorry, but I don't understand what is the purpose of setting `provider.MinValue`? Its default value is LogLevel.Debug: https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerProvider.cs
> so FilterLoggerProvider doesn't filter anything on its side - and normally filtering is performed by the logging infrastructure that takes into account "Logging":"LogLevel" config section (it is NOT intended for reading by the logging provider implementations).

You are absolutely right.

I was reading the default value from appsettings.json because the "Trace" level don´t logs anything on file.

Now i change the default value to LogLevel.Trace on FileLoggerProvider, and it's working.
