### ISSUE TITLE
AddFile(fileName, append) does not works as expected

### ISSUE THREAD

**Issue by KonH** [nreco/logging#2]
AddFile(fileName, false) and AddFile(fileName, true) are works in the same way. When 'append = false' is expected behaviour is: 

- First launch logs is saved to file
- Next launch logs is saved to file, but previous logs are removed and does not present in file

Can you please look at this problem?

**Comment by VitaliyMF** [comment]
@KonH for some reason "append" parameter was ignored in FileLoggerProvider class. Now it works as expected (I've added unit test for append=false use case). New version 1.0.2 is published on nuget.org.
Thank you for the bug report.
