### ISSUE TITLE
Rolling file with Date variable from appsettings.json

### ISSUE THREAD

**Issue by galdaka** [nreco/logging#21]
¿Is posible configure name of file with Date?

    "File": {
      "Path": "logs\\app_{0:yyyy}-{0:MM}-{0:dd}.log",
      "Append": "True",
      "FileSizeLimitBytes": 1048576, // use to activate rolling file behaviour 1MB
      "MaxRollingFiles": 5 // use to specify max number of log files
    }

**Comment by VitaliyMF** [comment]
To resolve 'variables' in the log file name you need to define `FormatLogFileName `handler in Startup.cs: https://github.com/nreco/logging#change-log-file-name-on-the-fly

**Comment by galdaka** [comment]
Hi,

What I intend is to unite the two characteristics: Rolling and custom format name in specific folder (Defined in appsettings.json). Is posible?

Thanks in advance,

**Comment by VitaliyMF** [comment]
> What I intend is to unite the two characteristics: Rolling and custom format name in specific folder (Defined in appsettings.json). Is posible?

This combination should work just fine.

**Comment by jhlight13** [comment]
> Hi,
> 
> What I intend is to unite the two characteristics: Rolling and custom format name in specific folder (Defined in appsettings.json). Is posible?
> 
> Thanks in advance,

Did you ever figure out how to do this?  If so, can you post it here?  I'm writing my first ASP.NET Core 6 application and wanted to add some logging, but can't figure out how to use a custom format name defined in appsettings.json and am having a difficult time finding any examples.
