### ISSUE TITLE
ImplementationType null injecting with .AddLogging() method

### ISSUE THREAD

**Issue by MindaugasBernatavicius** [nreco/logging#29]
Not yet sure why, but ImplementationType null injecting with .AddLogging() method.
Advice would be appreciated. Also is there a simpler way of configuring this logging library with DI?

Screenshot:
![image](https://user-images.githubusercontent.com/7895269/135697779-05334646-b98c-4b03-b060-332546b6744a.png)

Minimal working example (uncomment the line that works):
```csharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using CsvHelper;
using CsvHelper.Configuration;
using Newtonsoft.Json;
using Microsoft.Extensions.DependencyInjection;
using NReco.Logging.File;
using Microsoft.Extensions.Logging;

class Program
{
    static void Main()
    {
        var services = new ServiceCollection();

        services
            //.AddSingleton<ILogger>(new FileLogger("app.log", new FileLoggerProvider("app.log")))
            .AddLogging(loggingBuilder => loggingBuilder.AddFile("app.log", append: true))
            .AddTransient<Appy>();

        var serviceProvider = services.BuildServiceProvider();

        var app = serviceProvider.GetService<Appy>();
        app.logSomething();
    }

}

class Appy
{
    private readonly ILogger _logger;

    public Appy(ILogger logger)
    {
        _logger = logger;
    }

    public void logSomething()
    {
        _logger.LogInformation($"MyApplication Started!");
    }
}
```

**Comment by VitaliyMF** [comment]
`AddFile` extension method is implemented here: https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerExtensions.cs

It works just fine when used in MVC Core Startup.cs. I'm not sure what is wrong in your code -- have you tried to use standard logging provider, say, AddConsole, and check how it works?

**Comment by MindaugasBernatavicius** [comment]
Yea, sorry my mistake, the logger did not have the generic param: _public Appy(ILogger<Appy> logger)_ ... late night coding.
