### ISSUE TITLE
Windows service log to executable path

### ISSUE THREAD

**Issue by pedrodagraca** [nreco/logging#33]
Is there a way of specifying that the relative path given by Path in the settings should be relative to the executable instead of c:\windows\system32 when running a console app as a Windows service?

**Comment by VitaliyMF** [comment]
Sure, you can specify `FormatLogFileName` handler and resolve relative file name as you need (in the same way as it is used in https://github.com/nreco/logging#change-log-file-name-on-the-fly).

**Comment by pedrodagraca** [comment]
Thanks for the feedback.
