### ISSUE TITLE
APIs Filtering 

### ISSUE THREAD

**Issue by khaled-ghub** [nreco/logging#34]
Firstly I'd like to thank you for your library,

I used it in the following way:
appsettings.json: contains the configuration
middleware.cs: contains the HttpContext and creates a Logger then use it to LogInforamtion 
StartUp.cs: two methods:
a. ConfigureServices: services.AddLogging and do the configuration
b. Configure : calls the middleware for the app

I want to know if there is any configuration or any way to check the API method type before I call the middleware?

Thank you.

**Comment by VitaliyMF** [comment]
Sorry, I'm not sure that I understand the question.

Usage of [ILogging interface](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/#create-logs) is pretty the same as in case of, say, standard Console logging provider. Rules for log entries filtering are also the same as for Console.

**Comment by VitaliyMF** [comment]
I guess this question is no longer actual, closing.
