### ISSUE TITLE
Missing logs in .NET

### ISSUE THREAD

**Issue by linusalnervik** [nreco/logging#44]
Hi.
When logging with a .NET application at the end of the program, the last logging is not committed to the file.
Could it be that the dispose method is not waiting for the writing to complete?
Have also noticed that when creating a new file for logging, creating a log event, and then closing the console, only a empty file is created, with no logging included.

**Comment by VitaliyMF** [comment]
FileLoggerProvider implements IDispose, and normally it should be called on the app shut down.
If you use Microsoft.Logging with DI container, it does that by default. If not, you might need to call `LoggerFactory.Dispose` explicitely on the app stop.

**Comment by linusalnervik** [comment]
Ok.
Well we do use Microsoft.Logging with DI container. But shouldn't the filewriter thread of the event keep the main thread (that call the disposal due to ending) from closing?

Right now the garbage collection seems to close out the filewriter thread to early.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
Från: Vitaliy Fedorchenko ***@***.***>
Skickat: tisdag 6 september 2022 18:53
Till: nreco/logging ***@***.***>
Kopia: Linus Alnervik ***@***.***>; Author ***@***.***>
Ämne: Re: [nreco/logging] Missing logs in .NET (Issue #44)


FileLoggerProvider implements IDispose, and normally it should be called on the app shut down.
If you use Microsoft.Logging with DI container, it does that by default. If not, you might need to call LoggerFactory.Dispose explicitely on the app stop.

**Comment by linusalnervik** [comment]
Hi again.
This code will only create an empty file.
```c#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

var serviceProvider = new ServiceCollection()
           .AddLogging(loggingBuilder => {
               loggingBuilder.AddFile("app.log", append: true);
           }).BuildServiceProvider();

var logger = serviceProvider.GetService<ILoggerFactory>()
           .CreateLogger<Program>();
logger.LogInformation("Starting application");
```

When adding this code in the end (forceing the main thread to wait some) the row is also commited to the file

```c#
Thread.Sleep(2000);
```

**Comment by VitaliyMF** [comment]
Do you call `serviceProvider.Dispose()` when your program ends?

**Comment by linusalnervik** [comment]
Ohh, my bad missed that one....

So then there is no issue with the code!
Thanks for help
