### ISSUE TITLE
logger every day

### ISSUE THREAD

**Issue by Sin333** [nreco/logging#6]
How to use your library to creating new *.log files every day

**Comment by VitaliyMF** [comment]
At this moment you cannot specify a template for the log file name (that relies on the current date).

This capability can be added in the following way:

- introduce 'LogFileNameFormat' delegate in FileLoggerOptions
- if this delegate is defined check for the new file name in FileLoggerProvider.CheckForNewLogFile method (right now it checks current log size if max limit is specified)
