### ISSUE TITLE
NReco's FileLoggerExtensions should NOT be in the Microsoft.Extensions.Logging namespace.

### ISSUE THREAD

**Issue by jwdonahue** [nreco/logging#61]
NReco's FileLoggerExtensions should NOT be in the Microsoft.Extensions.Logging namespace.

The Microsoft and System namespaces are reserved for Microsoft's use.  You can extend their classes in your own namespace, or issue a PR to the appropriate .NET repo, and avoid creating many hard to debug issues in your customer's code.  What will you do if Microsoft decides to add an AddFile method of their own making to ILoggingBuilder?  Ya, that's unlikely, but what about all the other third parties out there?  Fixing this is probably a breaking change for you, but the sooner you take that hit, the better for everybody in the .NET ecosystem.

https://softwareengineering.stackexchange.com/a/400198/286679
https://stackoverflow.com/a/3991281/3150445

**Comment by VitaliyMF** [comment]
Shipped in 1.2.0
