### ISSUE TITLE
.NET Framework 4.8 support?

### ISSUE THREAD

**Issue by sbertolinconsejo** [nreco/logging#64]
Hi there,

Would it be possible to add support to .NET48, for those who cannot update? It seems to work adding this to the project file (and adding net48 to the targets):
```
 <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="7.*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.*" />
  </ItemGroup>
```

Thanks for this awesome project!

**Comment by VitaliyMF** [comment]
@sbertolinconsejo if you already tested that and NReco.Logging.File works fine in your .NET Framework 4.8 project lets add 'net48' target into the list.

Feel free to submit PR with these changes.

**Comment by sbertolinconsejo** [comment]
Hi @VitaliyMF I tried to create a branch in order to do a PR with no success, I think I don't have enough permissions to do that. I'm newbie on GitHub, maybe I'm doing something wrong. Thanks

**Comment by tomap** [comment]
> Hi @VitaliyMF I tried to create a branch in order to do a PR with no success, I think I don't have enough permissions to do that. I'm newbie on GitHub, maybe I'm doing something wrong. Thanks

Hello, you need to fork this repository, then you'll have enough rights to do that on your fork, and you'll be able to submit a pull request from this fork easily

**Comment by tomap** [comment]
But I believe the better version of .Net framework to support is .Net 4.7.2
(.Net 4.8 brings almost nothing interesting from an API standpoint, and anyone with .Net 4.7.2+ (any version above 4.7.2) will automatically use the upper version)
However, it can make it difficult for other libraries to integrate it if you use .Net 4.8
