### ISSUE TITLE
Logging file locked by nreco

### ISSUE THREAD

**Issue by Demsei** [nreco/logging#65]
Hi,
we want to collect all logging files and zip them. If the logging process is running, the logging file is locked so another process is not able to zip it. 
That can we do? Stopping the process is not so good.
thx

**Comment by VitaliyMF** [comment]
How do you copy log files? You should be able to copy 'active' log file (that is currently in use by the app) if it is opened for 'read'.
I tested that both on Windows and Linux.

Take a look at line 219 [here](https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerProvider.cs#L219C25-L219C35) where a file logger creates a `FileStream`:

```
LogFileStream = new FileStream(LogFileName, FileMode.OpenOrCreate, FileAccess.Write);
```

`FileShare` is not specified but by default it is `FileShare.Read` which allows other processes to open the file for 'read'.

**Comment by Demsei** [comment]
Hi,
I can copy active file in explorer as you mentioned. 
We try to open the active logfile in cabinet callback fnFileOpen with CreateFileA(fileName, GENERIC_READ, FILE_SHARE_READ, OPEN_EXISTING, FILE_ATTRIBUE_READONLY, nullptr). The result is INVALID_FILE_HANDLE and a call to GetLastError givs us rc=32 (ERROR_SHARING_VIOLATION).
What can we do else ?

**Comment by VitaliyMF** [comment]
Have you tried to specify FILE_SHARE_READ|FILE_SHARE_WRITE ? It's not obvious but this sharing mode is less restrictive than just FILE_SHARE_READ (which does NOT allow other processes to write into the file, therefore you get ERROR_SHARING_VIOLATION).

**Comment by Demsei** [comment]
bingo! that's it !!
You are me todays HERO
thx
