### ISSUE TITLE
How to write files of different log levels to different files.

### ISSUE THREAD

**Issue by bxjg1987** [nreco/logging#67]
For example:
Debug    Write to ：debug0. log, debug1. log
Error      Write to： error 0. log, error 1. log
How should I write appsettings
Also, this library is simpler than nlog serilog and I really like it! Thank you to the author.

**Comment by VitaliyMF** [comment]
You can add multiple file loggers and each of them can have its own configuration - not only filename but also FilterLogEntry handler (see [FileLoggerOptions](https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerOptions.cs)). In particular, this handler can check `LogMessage.LogLevel` and it this way write only, say, Debug entries into concrete log file.

**Comment by bxjg1987** [comment]
This is great. Thanks again!
