### ISSUE TITLE
How to get an instance of logger without injection?

### ISSUE THREAD

**Issue by DevelAx** [nreco/logging#7]
In ASP.NET Core 3.0 injection is [limited](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#hostbuilder-replaces-webhostbuilder) for the `Startup` constructor:

> The most significant change from `WebHostBuilder` to `HostBuilder` is in dependency injection (DI). When using `HostBuilder`, you can only inject `IConfiguration` and `IHostingEnvironment` into `Startup`'s constructor.

Is it possible to get an instance of logger without injection in cases like this one?

**Comment by VitaliyMF** [comment]
Sorry, I cannot understand how this change affects logger providers setup? They are configured in 'ConfigureServices' method, and may be injected only to services configured inside DI container.

**Comment by DevelAx** [comment]
I think you're right, it's not about `NReco.Logging.File`. It's about getting access to a service from the `Startup` constructor which doesn't seem to be possible now.
